image: java:8

cache:
  paths:
    - "${CI_PROJECT_DIR}/.ivy"

before_script:
    - apt-get update && apt-get install -y ant chromedriver
    - wget -q https://storage.googleapis.com/gwt-releases/gwt-2.8.2.zip && unzip -qq -o -d .. gwt-2.8.2.zip
    - wget -q https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip && unzip -qq -d .. chromedriver_linux64.zip
    - (cd vendor && wget -q https://builds.apache.org/job/Ivy/lastStableBuild/artifact/build/artifact/jars/ivy.jar)

stages:
    - test
    - deploy
    - tex

testjob:
    stage: test
    script:
        - ant test -lib vendor

deployjob:
    stage: deploy
    only:
        - master
    script:
        - git rev-parse --short HEAD > war/VERSION
        - ant war -lib vendor
        - curl -F 'war=@aurora.war' "https://aurora.younishd.fr:8080?key=$DEPLOY_KEY"

texjob:
    stage: tex
    image: blang/latex
    only:
        - master
    before_script:
        - echo "nop"
    script:
        - pdflatex -output-directory docs/implementierung/tex docs/implementierung/tex/Implementierungsdokument.tex && pdflatex -output-directory docs/implementierung/tex docs/implementierung/tex/Implementierungsdokument.tex
    artifacts:
        paths:
            - "docs/implementierung/tex/Implementierungsdokument.pdf"
