image: blang/latex

before_script:
  - apt-get update -qq && apt-get install -y -qq build-essential plantuml

entwurfsdokument:
  script:
    - cd docs/entwurf/tex && latexmk -f -pdf Entwurf.tex
  artifacts:
    paths:
      - "docs/entwurf/tex/Entwurf.pdf"
