image: blang/latex

before_script:
  - apt-get update -qq && apt-get install -y -qq build-essential plantuml wget openjdk-8-jdk
  - wget http://doclet.github.io/resources/bin/TeXDoclet.jar

entwurfsdokument:
  script:
    - cd docs/entwurf/tex && latexmk -f -pdf Entwurf.tex
    - mkdir -p out && javadoc -output out/classes.tex -docletpath ../../../TeXDoclet.jar -doclet org.stfm.texdoclet.TeXDoclet $(find ../../../src -name '*.java')
    - pdflatex -output-directory=out classes.tex && pdflatex -output-directory=out classes.tex
  artifacts:
    paths:
      - "docs/entwurf/tex/Entwurf.pdf"
      - "docs/entwurf/tex/out/classes.pdf"
