image: ubuntu:xenial

before_script:
  - apt-get update && apt-get install -y build-essential openjdk-8-jdk ant ivy wget unzip
  - wget -q https://storage.googleapis.com/gwt-releases/gwt-2.8.2.zip && unzip -qq -o -d .. gwt-2.8.2.zip

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - ant build

test:
  stage: test
  script:
    - ant cs

deploy:
  stage: deploy
  script:
    - echo "Deploying..."
