language: java
before_install:
    - sudo apt-get update && sudo apt-get install -y ant openjfx unzip
    - wget -q https://storage.googleapis.com/gwt-releases/gwt-2.8.2.zip && unzip -qq -o -d .. gwt-2.8.2.zip
    - wget -q https://builds.apache.org/job/Ivy/lastStableBuild/artifact/build/artifact/jars/ivy.jar
    - wget -q https://github.com/mholt/caddy/releases/download/v0.10.11/caddy_v0.10.11_linux_amd64.tar.gz && tar xzf caddy_v0.10.11_linux_amd64.tar.gz
install:
    - nohup ./caddy &
    - ant test-ci -lib .
