language: java
dist: trusty
sudo: required
before_install:
    - sudo apt-get update && sudo apt-get install -y ant unzip
    - wget -q https://storage.googleapis.com/gwt-releases/gwt-2.8.2.zip && unzip -qq -o -d .. gwt-2.8.2.zip
    - wget -q https://builds.apache.org/job/Ivy/lastStableBuild/artifact/build/artifact/jars/ivy.jar
script:
    - ant -debug test-ci -lib .
jdk:
    - openjdk8
